FROM registry.access.redhat.com/ubi8/python-36

EXPOSE 8080

ENV LC_ALL="en_US.UTF-8" \
    LANG="en_US.UTF-8" \
    APP_ROOT="/opt/app-root"

# Copy extra files to the image
COPY ./root/ /

WORKDIR ${APP_ROOT}

COPY forever_recv.py send.py oc_rsend oc_freceive /

# Drop the root user and make the content of /opt/app-root owned by user 1001
RUN chown -R 1001:0 ${APP_ROOT} && chmod -R ug+rwx ${APP_ROOT}

USER 1001

CMD ["run"]