apiVersion: v1
kind: List
items:

- kind: DeploymentConfig
  apiVersion: 'v1'
  metadata:
    labels:
      app: aws-iot-mqtt
    name: aws-iot-mqtt
  spec:
    replicas: 1
    selector:
      app: aws-iot-mqtt
      deploymentconfig: aws-iot-mqtt
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: aws-iot-mqtt
          deploymentconfig: aws-iot-mqtt
      spec:
        containers:
          - env:
            
            - name: ENDPOINT
              value: 'a36ob0439j5iyd-ats.iot.eu-central-1.amazonaws.com'
            - name: CLIENT_ID
              value: pod-mqtt-subscriber
            - name: TOPIC
              value: cloudpi/test
            - name: ROOT_CA_PATH
              value: certs/ca/root-CA.crt
            - name: CERT_PATH
              value: certs/cert/cloudpi.cert.pem
            - name: KEY_PATH
              value: certs/key/cloudpi.private.key
            - name: EXTRA_PARAMS
              value: ''
            - name: SCRIPT
              value: src/mqtt_subscriber.py

            volumeMounts:
            - name: cv-rootca
              mountPath: /opt/app-root/certs/ca
            - name: cv-cert
              mountPath: /opt/app-root/certs/cert
            - name: cv-key
              mountPath: /opt/app-root/certs/key

            image: ubi8-aws-iot-mqtt:latest
            imagePullPolicy: Always
            name: aws-iot-mqtt
            resources: {}
        
        volumes:
          - name: cv-rootca
            configMap:
              name: root-ca
              items:
              - key: root-CA.crt
                path: root-CA.crt
          
          - name: cv-cert
            configMap:  
              name: cloudpi-cert
              items:
              - key: cloudpi00.cert.pem
                path: cloudpi.cert.pem
          
          - name: cv-key
            configMap:  
              name: cloudpi-key
              items:
              - key: cloudpi00.private.key
                path: cloudpi.private.key

    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - aws-iot-mqtt
        from:
          kind: ImageStreamTag
          name: ubi8-aws-iot-mqtt:latest
      type: ImageChange
